GET http://127.0.0.1:3000/api/private-get-route HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbGY3MGZ4Z20wMDAwOWtwaWMwa2ZmOWZwIiwiaWF0IjoxNjc4ODg4MTM0LCJleHAiOjE2ODE0ODAxMzR9.OLEE8urgWWIG8A9WGt3XfQpPBiKnYFIngR3yq9nuZCc
# correct eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbGY3MGZ4Z20wMDAwOWtwaWMwa2ZmOWZwIiwiaWF0IjoxNjc4ODg4MTM0LCJleHAiOjE2ODE0ODAxMzR9.OLEE8urgWWIG8A9WGt3XfQpPBiKnYFIngR3yq9nuZCc
# incorrect eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbGY3MGZ4Z20wMDAwOWtwaWMwa2ZmOWZwIiwiaWF0IjoxNjc4NzIzMjI1LCJleHAiOjE2Nzg3NjY0MjV9.IbSW7spM6Z35Il7jVDNUbXsBzbM-_Xw2rBJpQvvI1nA